-- =============================================
-- updated_at 자동 갱신 트리거 함수
-- =============================================
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- =============================================
-- 1. users (사용자)
-- =============================================
CREATE TABLE users (
    id             VARCHAR(36)   NOT NULL,
    email          VARCHAR(100)  NOT NULL,
    password       VARCHAR(255)  NULL,
    name           VARCHAR(50)   NOT NULL,
    phone          VARCHAR(20)   NULL,
    role           VARCHAR(20)   NOT NULL,
    status         VARCHAR(20)   NOT NULL DEFAULT 'ACTIVE',
    provider       VARCHAR(20)   NOT NULL DEFAULT 'LOCAL',
    provider_id    VARCHAR(100)  NULL,
    profile_image  VARCHAR(500)  NULL,
    email_verified BOOLEAN       NOT NULL DEFAULT FALSE,
    prev_password1 VARCHAR(255)  NULL,
    prev_password2 VARCHAR(255)  NULL,
    last_login_at  TIMESTAMPTZ   NULL,
    created_at     TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    updated_at     TIMESTAMPTZ   NOT NULL DEFAULT NOW(),

    CONSTRAINT pk_users           PRIMARY KEY (id),
    CONSTRAINT uq_users_email     UNIQUE (email),
    CONSTRAINT chk_users_role     CHECK (role     IN ('WARD', 'GUARDIAN', 'ADMIN')),
    CONSTRAINT chk_users_status   CHECK (status   IN ('ACTIVE', 'INACTIVE')),
    CONSTRAINT chk_users_provider CHECK (provider IN ('LOCAL', 'KAKAO'))
);

CREATE TRIGGER trg_users_updated_at
    BEFORE UPDATE ON users
    FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- =============================================
-- 2. refresh_tokens (리프레시 토큰)
-- =============================================
CREATE TABLE refresh_tokens (
    id         BIGINT        NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id    VARCHAR(36)   NOT NULL,
    token      VARCHAR(500)  NOT NULL,
    expires_at TIMESTAMPTZ   NOT NULL,
    created_at TIMESTAMPTZ   NOT NULL DEFAULT NOW(),

    CONSTRAINT pk_refresh_tokens       PRIMARY KEY (id),
    CONSTRAINT uq_refresh_tokens_token UNIQUE (token),
    CONSTRAINT fk_refresh_tokens_user  FOREIGN KEY (user_id)
        REFERENCES users(id) ON DELETE CASCADE
);

-- =============================================
-- 3. access_logs (접속 로그)
-- =============================================
CREATE TABLE access_logs (
    id         BIGINT        NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id    VARCHAR(36)   NULL,
    client_id  VARCHAR(36)   NULL,
    action     VARCHAR(50)   NOT NULL,
    ip_address VARCHAR(50)   NULL,
    user_agent VARCHAR(500)  NULL,
    created_at TIMESTAMPTZ   NOT NULL DEFAULT NOW(),

    CONSTRAINT pk_access_logs      PRIMARY KEY (id),
    CONSTRAINT fk_access_logs_user FOREIGN KEY (user_id)
        REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT chk_access_logs_action CHECK (
        action IN ('LOGIN', 'LOGOUT', 'KAKAO_LOGIN', 'TOKEN_ISSUE', 'PASSWORD_RESET')
    )
);

-- =============================================
-- 4. sso_clients (등록된 서비스)
-- =============================================
CREATE TABLE sso_clients (
    id            BIGINT        NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    client_id     VARCHAR(100)  NOT NULL,
    client_name   VARCHAR(100)  NOT NULL,
    client_secret VARCHAR(255)  NOT NULL,
    redirect_uri  VARCHAR(500)  NOT NULL,
    is_active     BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMPTZ   NOT NULL DEFAULT NOW(),

    CONSTRAINT pk_sso_clients           PRIMARY KEY (id),
    CONSTRAINT uq_sso_clients_client_id UNIQUE (client_id)
);

CREATE TRIGGER trg_sso_clients_updated_at
    BEFORE UPDATE ON sso_clients
    FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- =============================================
-- 인덱스
-- =============================================
CREATE INDEX idx_refresh_tokens_user_id ON refresh_tokens(user_id);
CREATE INDEX idx_access_logs_user_id    ON access_logs(user_id);
CREATE INDEX idx_access_logs_created_at ON access_logs(created_at);
CREATE INDEX idx_users_provider_id      ON users(provider, provider_id);


-- =============================================
-- Redis 키 구조 (참고용)
-- =============================================
-- 이메일 인증코드:
--   key:   email:verify:{email}
--   value: "123456"
--   TTL:   300초 (5분)
--
-- 비밀번호 재설정:
--   key:   password:reset:{token}
--   value: "{userId}"
--   TTL:   1800초 (30분)
--
-- 로그아웃된 토큰:
--   key:   logout:{accessToken}
--   value: "true"
--   TTL:   토큰 남은 만료시간
