-- =============================================
-- updated_at 자동 갱신 트리거 함수
-- =============================================
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- =============================================
-- 1. users (사용자)
-- =============================================
CREATE TABLE users (
    id             VARCHAR(36)   NOT NULL,
    email          VARCHAR(100)  NOT NULL,
    password       VARCHAR(255)  NULL,
    name           VARCHAR(50)   NOT NULL,
    phone          VARCHAR(20)   NULL,
    role           VARCHAR(20)   NOT NULL,
    status         VARCHAR(20)   NOT NULL DEFAULT 'ACTIVE',
    provider       VARCHAR(20)   NOT NULL DEFAULT 'LOCAL',
    provider_id    VARCHAR(100)  NULL,
    profile_image  VARCHAR(500)  NULL,
    prev_password1 VARCHAR(255)  NULL,
    prev_password2 VARCHAR(255)  NULL,
    last_login_at  TIMESTAMPTZ   NULL,
    created_at     TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    updated_at     TIMESTAMPTZ   NOT NULL DEFAULT NOW(),

    CONSTRAINT pk_users           PRIMARY KEY (id),
    CONSTRAINT uq_users_email     UNIQUE (email),
    CONSTRAINT chk_users_role     CHECK (role     IN ('WARD', 'GUARDIAN', 'ADMIN')),
    CONSTRAINT chk_users_status   CHECK (status   IN ('ACTIVE', 'INACTIVE', 'PENDING')),
    CONSTRAINT chk_users_provider CHECK (provider IN ('LOCAL', 'KAKAO'))
);

CREATE TRIGGER trg_users_updated_at
    BEFORE UPDATE ON users
    FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- =============================================
-- 2. refresh_tokens (리프레시 토큰)
-- =============================================
CREATE TABLE refresh_tokens (
    id         BIGINT        NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id    VARCHAR(36)   NOT NULL,
    token      VARCHAR(500)  NOT NULL,
    expires_at TIMESTAMPTZ   NOT NULL,
    created_at TIMESTAMPTZ   NOT NULL DEFAULT NOW(),

    CONSTRAINT pk_refresh_tokens       PRIMARY KEY (id),
    CONSTRAINT uq_refresh_tokens_token UNIQUE (token),
    CONSTRAINT fk_refresh_tokens_user  FOREIGN KEY (user_id)
        REFERENCES users(id) ON DELETE CASCADE
);

-- =============================================
-- 3. access_logs (접속 로그)
-- =============================================
CREATE TABLE access_logs (
    id         BIGINT        NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id    VARCHAR(36)   NULL,
    action     VARCHAR(50)   NOT NULL,
    ip_address VARCHAR(50)   NULL,
    user_agent VARCHAR(500)  NULL,
    created_at TIMESTAMPTZ   NOT NULL DEFAULT NOW(),

    CONSTRAINT pk_access_logs      PRIMARY KEY (id),
    CONSTRAINT fk_access_logs_user FOREIGN KEY (user_id)
        REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT chk_access_logs_action CHECK (
        action IN ('LOGIN', 'LOGOUT', 'KAKAO_LOGIN', 'TOKEN_ISSUE', 'PASSWORD_RESET')
    )
);

-- =============================================
-- 4. connections (보호자-피보호자 연결)
-- =============================================
CREATE TABLE connections (
    id           BIGINT      NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    guardian_id  VARCHAR(6)  NOT NULL,
    ward_id      VARCHAR(6)  NOT NULL,
    status       VARCHAR(20) NOT NULL DEFAULT 'PENDING', -- PENDING, ACTIVE, CANCELLED
    initiated_by VARCHAR(6)  NULL,                        -- 요청한 사용자 ID (탈퇴 시 NULL)
    priority     INT         NOT NULL DEFAULT 1,           -- 피보호자 기준 보호자 통화 우선순위 (1=1순위)
    connected_at TIMESTAMPTZ NULL,                       -- ACTIVE 전환 시각
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT pk_connections           PRIMARY KEY (id),
    CONSTRAINT fk_connections_guardian  FOREIGN KEY (guardian_id)  REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_connections_ward      FOREIGN KEY (ward_id)      REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_connections_init      FOREIGN KEY (initiated_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT chk_connections_status   CHECK (status IN ('PENDING', 'ACTIVE', 'CANCELLED')),
    CONSTRAINT chk_connections_priority CHECK (priority >= 1)
);

CREATE TRIGGER trg_connections_updated_at
    BEFORE UPDATE ON connections
    FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- =============================================
-- 5. anomaly_events (이상감지 이벤트)
-- =============================================
CREATE TABLE anomaly_events (
    id           BIGINT        NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    ward_id      VARCHAR(36)   NULL,
    event_type   VARCHAR(20)   NOT NULL,               -- FIRE, WEAPON, FALL
    confidence   DECIMAL(5, 2) NOT NULL,               -- 감지도 (0.00 ~ 1.00)
    detected_at  TIMESTAMPTZ   NOT NULL,
    is_confirmed BOOLEAN       NOT NULL DEFAULT FALSE, -- 보호자/관리자 확인 여부
    created_at   TIMESTAMPTZ   NOT NULL DEFAULT NOW(),

    CONSTRAINT pk_anomaly_events       PRIMARY KEY (id),
    CONSTRAINT fk_anomaly_events_ward  FOREIGN KEY (ward_id) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT chk_anomaly_events_type CHECK (event_type IN ('FIRE', 'WEAPON', 'FALL'))
);

-- =============================================
-- 6. game_results (게임 결과)
-- =============================================
CREATE TABLE game_results (
    id               BIGINT      NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id          VARCHAR(36) NOT NULL,
    game_type        VARCHAR(30) NOT NULL,  -- MATCHING, WORD_QUIZ, ADDITION, SUBTRACTION
    difficulty       INT         NOT NULL DEFAULT 1,
    is_cleared       BOOLEAN     NOT NULL,
    score            INT         NULL,
    duration_seconds INT         NULL,
    played_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT pk_game_results       PRIMARY KEY (id),
    CONSTRAINT fk_game_results_user  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT chk_game_results_type CHECK (game_type IN ('MATCHING', 'WORD_QUIZ', 'ADDITION', 'SUBTRACTION'))
);

-- =============================================
-- 7. hospital_reservations (병원 예약)
-- =============================================
CREATE TABLE hospital_reservations (
    id                      BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id                 VARCHAR(36)  NOT NULL,
    external_reservation_id VARCHAR(100) NULL,       -- 외부 예약 시스템 ID
    hospital_name           VARCHAR(200) NOT NULL,
    department              VARCHAR(100) NULL,       -- 진료과
    doctor_name             VARCHAR(100) NULL,
    appointment_at          TIMESTAMPTZ  NOT NULL,
    status                  VARCHAR(20)  NOT NULL DEFAULT 'PENDING', -- PENDING, CONFIRMED, CANCELLED, COMPLETED
    notes                   VARCHAR(500) NULL,
    created_at              TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at              TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    CONSTRAINT pk_hospital_reservations        PRIMARY KEY (id),
    CONSTRAINT fk_hospital_reservations_user   FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT chk_hospital_reservations_status CHECK (status IN ('PENDING', 'CONFIRMED', 'CANCELLED', 'COMPLETED'))
);

CREATE TRIGGER trg_hospital_reservations_updated_at
    BEFORE UPDATE ON hospital_reservations
    FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- =============================================
-- 8. announcements (공지)
-- =============================================
CREATE TABLE announcements (
    id           BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    author_id    VARCHAR(36)  NULL,
    title        VARCHAR(200) NOT NULL,
    content      TEXT         NOT NULL,
    is_published BOOLEAN      NOT NULL DEFAULT FALSE,
    published_at TIMESTAMPTZ  NULL,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    CONSTRAINT pk_announcements        PRIMARY KEY (id),
    CONSTRAINT fk_announcements_author FOREIGN KEY (author_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TRIGGER trg_announcements_updated_at
    BEFORE UPDATE ON announcements
    FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- =============================================
-- 9. admin_audit_logs (관리자 행동 감사 로그)
-- =============================================
CREATE TABLE admin_audit_logs (
    id         BIGINT        NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    admin_id   VARCHAR(36)   NOT NULL,                   -- 행동한 관리자 ID (탈퇴 시에도 이력 보존, FK 없음)
    action     VARCHAR(30)   NOT NULL,                   -- 행동 유형 (AdminAuditAction enum)
    target_id  VARCHAR(100)  NULL,                       -- 대상 ID (userId / connectionId / announcementId)
    detail     VARCHAR(500)  NULL,                       -- 변경 내용 요약
    created_at TIMESTAMPTZ   NOT NULL DEFAULT NOW(),

    CONSTRAINT pk_admin_audit_logs       PRIMARY KEY (id),
    CONSTRAINT chk_admin_audit_action    CHECK (action IN (
        'USER_STATUS_CHANGE', 'USER_ROLE_CHANGE', 'USER_FORCE_DELETE',
        'FORCE_CONNECT', 'FORCE_DISCONNECT',
        'ANNOUNCEMENT_CREATE', 'ANNOUNCEMENT_UPDATE', 'ANNOUNCEMENT_PUBLISH', 'ANNOUNCEMENT_DELETE'
    ))
);

-- =============================================
-- 10. fcm_tokens (FCM 푸시 알림 토큰)
-- =============================================
CREATE TABLE fcm_tokens (
    id         BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id    VARCHAR(6)   NOT NULL,
    token      VARCHAR(500) NOT NULL,
    platform   VARCHAR(10)  NOT NULL DEFAULT 'ANDROID', -- ANDROID, IOS, WEB
    created_at TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    CONSTRAINT pk_fcm_tokens           PRIMARY KEY (id),
    CONSTRAINT uq_fcm_tokens_token     UNIQUE (token),
    CONSTRAINT fk_fcm_tokens_user      FOREIGN KEY (user_id)
        REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT chk_fcm_tokens_platform CHECK (platform IN ('ANDROID', 'IOS', 'WEB'))
);

CREATE TRIGGER trg_fcm_tokens_updated_at
    BEFORE UPDATE ON fcm_tokens
    FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- =============================================
-- 인덱스
-- =============================================
CREATE INDEX idx_users_email                          ON users(email);
CREATE UNIQUE INDEX uq_users_phone                    ON users(phone) WHERE phone IS NOT NULL;
CREATE INDEX idx_users_provider_id                    ON users(provider, provider_id);
CREATE INDEX idx_refresh_tokens_user_id               ON refresh_tokens(user_id);
CREATE INDEX idx_access_logs_user_id                  ON access_logs(user_id);
CREATE INDEX idx_access_logs_created_at               ON access_logs(created_at);

-- 동일 guardian-ward 쌍의 ACTIVE/PENDING 중복 방지 (CANCELLED 상태는 재연결 허용)
CREATE UNIQUE INDEX uq_connections_active             ON connections(guardian_id, ward_id) WHERE status != 'CANCELLED';
CREATE INDEX idx_connections_guardian_id              ON connections(guardian_id);
CREATE INDEX idx_connections_ward_id                  ON connections(ward_id);
CREATE INDEX idx_connections_status                   ON connections(status);

CREATE INDEX idx_anomaly_events_ward_id               ON anomaly_events(ward_id);
CREATE INDEX idx_anomaly_events_detected_at           ON anomaly_events(detected_at);
CREATE INDEX idx_anomaly_events_ward_detected         ON anomaly_events(ward_id, detected_at);
CREATE INDEX idx_game_results_user_id                 ON game_results(user_id);
CREATE INDEX idx_game_results_played_at               ON game_results(played_at);
CREATE INDEX idx_game_results_user_type               ON game_results(user_id, game_type);
CREATE INDEX idx_hospital_reservations_user_id        ON hospital_reservations(user_id);
CREATE INDEX idx_hospital_reservations_appointment_at ON hospital_reservations(appointment_at);
CREATE INDEX idx_announcements_is_published           ON announcements(is_published);
CREATE INDEX idx_admin_audit_logs_admin_created       ON admin_audit_logs(admin_id, created_at);
CREATE INDEX idx_fcm_tokens_user_id                   ON fcm_tokens(user_id);

-- =============================================
-- Redis 키 구조 (참고용, RedisKeys.java 기준)
-- =============================================
-- 회원가입 SMS 인증:
--   sms:verify:{phone}    → 인증코드 (TTL 5분)
--   sms:verified:{phone}  → 인증 완료 상태 (TTL 10분)
--   sms:cooldown:{phone}  → 재발송 쿨다운 (TTL 1분)
--   sms:attempt:{phone}   → 오류 횟수 (TTL 5분)
--
-- 비밀번호 재설정:
--   password:reset:{token}        → userId (TTL 30분)
--   password:sms:verify:{phone}   → 인증코드 (TTL 5분)
--   password:sms:cooldown:{phone} → 재발송 쿨다운 (TTL 1분)
--   password:sms:attempt:{phone}  → 오류 횟수 (TTL 5분)
--
-- 카카오 신규 가입:
--   kakao:pending:{kakaoId} → 이메일 (TTL 10분)
--
-- 로그인 보안:
--   login:fail:{email} → 실패 횟수 (TTL 30분)
--   login:lock:{email} → 잠금 상태 (TTL 30분)
--
-- 로그아웃 블랙리스트:
--   logout:{accessToken} → "true" (TTL 토큰 남은 만료시간)
