-- 공지 임시저장 테이블 (게시 전 작성 중인 공지)
-- 게시 시점에 announcements 로 이동하고 본 테이블의 행은 삭제된다.
CREATE TABLE announcement_drafts (
    id         BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    author_id  VARCHAR(6)   NULL,
    title      VARCHAR(200) NOT NULL,
    content    TEXT         NOT NULL,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    CONSTRAINT pk_announcement_drafts        PRIMARY KEY (id),
    CONSTRAINT fk_announcement_drafts_author FOREIGN KEY (author_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TRIGGER trg_announcement_drafts_updated_at
    BEFORE UPDATE ON announcement_drafts
    FOR EACH ROW EXECUTE FUNCTION update_updated_at();

CREATE INDEX idx_announcement_drafts_author_id  ON announcement_drafts(author_id);
CREATE INDEX idx_announcement_drafts_created_at ON announcement_drafts(created_at DESC);