-- 피보호자 SOS 발생 이력. 피보호자가 긴급 SOS 버튼을 누를 때마다 한 행이 기록된다.
-- 발송된 보호자 목록은 저장하지 않는다 — 긴급 알림은 이력 커밋 후(AFTER_COMMIT)에 발송되며,
-- 알림 대상 보호자는 발송 시점의 connections(ACTIVE)에서 도출된다(정규화 유지, 저장 시점엔 미확정).
-- ward_id 는 회원 탈퇴(hard delete) 시 익명 보존을 위해 ON DELETE SET NULL — access_logs 와 동일 정책.
CREATE TABLE sos_events (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ward_id    VARCHAR(6) NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_sos_events_ward FOREIGN KEY (ward_id) REFERENCES users (id) ON DELETE SET NULL
);

CREATE INDEX idx_sos_events_ward_created ON sos_events (ward_id, created_at DESC);
