-- 고객센터 문의(inquiry). 보호자가 작성하고 관리자가 답변한다.
-- user_id 는 작성자(보호자). 회원 탈퇴(hard delete) 시 본인 문의도 함께 제거되도록 ON DELETE CASCADE
--   (connections 와 동일 정책 — 탈퇴자 소유 데이터는 함께 정리, 별도 리스너 불필요).
-- answered_by 는 답변 관리자. 관리자 계정 삭제 시에도 답변 내용은 보존하도록 ON DELETE SET NULL.
CREATE TABLE inquiries (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     VARCHAR(6)   NOT NULL,
    category    VARCHAR(20)  NOT NULL,
    title       VARCHAR(100) NOT NULL,
    content     TEXT         NOT NULL,
    status      VARCHAR(20)  NOT NULL DEFAULT 'WAITING',
    answer      TEXT         NULL,
    answered_by VARCHAR(6)   NULL,
    answered_at TIMESTAMPTZ  NULL,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT fk_inquiries_user        FOREIGN KEY (user_id)     REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_inquiries_answered_by FOREIGN KEY (answered_by) REFERENCES users (id) ON DELETE SET NULL
);

-- 보호자 본인 문의 목록 조회 (user_id 필터 + 최신순)
CREATE INDEX idx_inquiries_user_created   ON inquiries (user_id, created_at DESC);
-- 관리자 탭 카운트 및 상태 필터 목록 (status 필터 + 최신순)
CREATE INDEX idx_inquiries_status_created ON inquiries (status, created_at DESC);
-- 관리자 카테고리 필터
CREATE INDEX idx_inquiries_category       ON inquiries (category);
