-- 이상감지 카메라 소유권. 소유자 = 피보호자(ward_id). 보호자는 connections(ACTIVE)로 전이 접근.
-- 피보호자당 여러 대(방별). session_id = 카메라 고유 세션(AI sessionId). device_id = 백엔드 발급 기기 토큰(FE localStorage).
-- label = 설치 위치(방 이름). 회원 탈퇴(hard delete) 시 ward_id ON DELETE CASCADE (connections/inquiries 동일 정책).
-- registered_by 는 등록 주체 — 등록자 계정 삭제 시에도 카메라는 소유자 기준 유지되도록 SET NULL.
CREATE TABLE cameras (
    id            BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ward_id       VARCHAR(6)  NOT NULL,
    session_id    VARCHAR(64) NOT NULL,
    device_id     VARCHAR(64) NOT NULL,
    label         VARCHAR(30) NOT NULL,
    registered_by VARCHAR(6)  NULL,
    is_active     BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_cameras_session       UNIQUE (session_id),
    CONSTRAINT uq_cameras_ward_device   UNIQUE (ward_id, device_id),
    CONSTRAINT fk_cameras_ward          FOREIGN KEY (ward_id)       REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_cameras_registered_by FOREIGN KEY (registered_by) REFERENCES users (id) ON DELETE SET NULL
);

-- 피보호자 본인 목록 / 보호자 allowlist(ward_id IN ...) 양쪽에 사용
CREATE INDEX idx_cameras_ward ON cameras (ward_id);
