-- AI 이상감지 이력. AI 서버 WebSocket(latest_analysis)에서 수신한 신호 중 "위험"으로 판정된 건만 적재한다.
-- 판정 = AI가 채운 danger 플래그(기본 DANGER 모드). AI 배포 지연 시에만 confidence 임계 폴백(CONFIDENCE 모드).
-- session_id = cameras.session_id (백엔드 발급) → ward_id 매핑. 미등록 세션 신호는 적재하지 않는다.
-- 같은 위험 1건이 매 프레임 broadcast로 수백 행이 되지 않도록 (session_id, detected_type) 쿨다운(Redis) 후 적재.
CREATE TABLE anomaly_events (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ward_id       VARCHAR(6)   NOT NULL,
    session_id    VARCHAR(64)  NOT NULL,
    detected_type VARCHAR(20)  NOT NULL,
    confidence    DOUBLE PRECISION NOT NULL,
    danger        BOOLEAN      NOT NULL,
    -- AI analyzedAt(naive UTC). 캐시 미스 fallback 페이로드엔 이 필드가 없을 수 있어 NULL 허용 —
    -- NULL이면 "AI 분석 시각 불명"이며 수신 시각은 created_at으로 남는다(둘을 섞지 않는다).
    detected_at   TIMESTAMPTZ  NULL,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT fk_anomaly_events_ward FOREIGN KEY (ward_id) REFERENCES users (id) ON DELETE CASCADE
);

-- 보호자/피보호자별 이상감지 이력 조회(최신순) — 2단계 알림·이력 API의 주 조회 경로
CREATE INDEX idx_anomaly_events_ward_created ON anomaly_events (ward_id, created_at DESC);
