-- 이상감지 "상황(incident)" 묶음 + 보호자 판정 스키마 복원 (2026-09-01)
--
-- 왜 V44인가: 같은 스키마를 V42가 만들었고 V43이 지웠다. 2026-08-31 회의 전 보류 결정으로
-- 되돌렸다가, 2026-09-01 대시보드를 기존 설계대로 가기로 확정해 다시 세운다.
-- V42·V43은 배포 서버 두 곳(vkcs-linux·gosky)에 모두 적용된 이력이 있어 파일을 지우거나 고칠 수 없다
-- (지우면 Flyway가 "적용됐지만 로컬에 없는 마이그레이션"으로 판단해 기동을 거부한다).
-- 되돌리기도, 되살리기도 앞으로 나아가는 마이그레이션으로 한다.
--
-- 안전한 이유: 두 서버 모두 V43까지 적용돼 세 객체가 없는 상태이고, anomaly_event도 0건이라
-- incident_id에 백필할 데이터가 없다. 스키마 내용은 V42와 동일하다.
--
-- 이 마이그레이션은 스키마만 세운다 - 수신·판정·쿨다운·발송 경로는 건드리지 않는다.

-- =============================================
-- 1. anomaly_incident (판정 단위)
-- =============================================
-- 왜 상황 단위인가: 같은 카메라에서 화재가 3분 이어지면 이력(anomaly_event)은 쿨다운 1분 간격으로
-- 3건이 쌓인다. 그걸 보호자에게 3번 물으면 안 되므로 연속 감지를 하나로 묶어 판정·통계의 단위로 삼는다.
CREATE TABLE anomaly_incident (
    id               BIGINT           GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ward_id          VARCHAR(6)       NOT NULL,
    -- 감지 시점의 cameras.session_id. anomaly_event와 같은 이유로 비정규화한다
    -- (카메라가 삭제·재발급돼도 과거 상황이 어느 세션 것인지 판독 가능해야 한다).
    session_id       VARCHAR(64)      NOT NULL,
    detected_type    VARCHAR(20)      NOT NULL,
    -- 첫 감지 / 마지막 감지 (수신 시각 기준 - AI analyzedAt은 fallback 페이로드에서 NULL일 수 있어
    -- 묶음 판정의 기준으로 쓸 수 없다).
    started_at       TIMESTAMPTZ      NOT NULL,
    last_detected_at TIMESTAMPTZ      NOT NULL,
    event_count      INT              NOT NULL DEFAULT 1,
    max_confidence   DOUBLE PRECISION NOT NULL,
    -- PENDING(응답 없음) / REAL(응답자 전원 실제 위험) / FALSE_ALARM(전원 오탐) / CONFLICTED(엇갈림)
    review_status    VARCHAR(20)      NOT NULL DEFAULT 'PENDING',
    -- 관리자 정정 기록. 채워지면 그 상태가 최종이며 이후 보호자 응답으로 재계산되지 않는다.
    resolved_by      VARCHAR(6)       NULL,
    resolved_at      TIMESTAMPTZ      NULL,
    review_note      VARCHAR(200)     NULL,
    created_at       TIMESTAMPTZ      NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ      NOT NULL DEFAULT now(),

    CONSTRAINT fk_anomaly_incident_ward     FOREIGN KEY (ward_id)     REFERENCES users (id) ON DELETE CASCADE,
    -- 정정한 관리자가 탈퇴해도 판정 결과 자체는 남긴다(누가 했는지만 사라진다).
    CONSTRAINT fk_anomaly_incident_resolver FOREIGN KEY (resolved_by) REFERENCES users (id) ON DELETE SET NULL,
    CONSTRAINT chk_anomaly_incident_status  CHECK (review_status IN ('PENDING', 'REAL', 'FALSE_ALARM', 'CONFLICTED'))
);

-- 보호자 이력 조회(피보호자별 최신순)
CREATE INDEX idx_anomaly_incident_ward_started   ON anomaly_incident (ward_id, started_at DESC);
-- 관리자 로그 페이지의 상태 필터(특히 CONFLICTED) + 대시보드 판정 집계
CREATE INDEX idx_anomaly_incident_status_started ON anomaly_incident (review_status, started_at DESC);
-- 상황 승계 판정: 같은 (ward, session, type)의 직전 상황 1건을 찾는다. 매 감지마다 도는 경로다.
CREATE INDEX idx_anomaly_incident_merge          ON anomaly_incident (ward_id, session_id, detected_type, last_detected_at DESC);

-- =============================================
-- 2. anomaly_event.incident_id (이력 → 상황)
-- =============================================
-- 기존 행은 채울 근거가 없어 NULL로 둔다(배포 2곳 모두 0건). NULL = "상황 묶음 도입 이전 이력"이며,
-- 판정 대상이 아니다. NOT NULL로 만들려면 백필이 필요한데 그 근거가 없다.
ALTER TABLE anomaly_event
    ADD COLUMN incident_id BIGINT NULL REFERENCES anomaly_incident (id) ON DELETE CASCADE;

CREATE INDEX idx_anomaly_event_incident ON anomaly_event (incident_id);

-- =============================================
-- 3. anomaly_incident_feedback (보호자 응답)
-- =============================================
-- 보호자 1인 1표. 번복은 UPDATE라 "언제 마음을 바꿨는지"는 남기지 않는다 - 필요한 것은 최종 판단뿐이다.
-- 판정 주체는 보호자뿐이다(피보호자 본인·관리자의 1차 판정은 없다).
CREATE TABLE anomaly_incident_feedback (
    id          BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    incident_id BIGINT      NOT NULL,
    guardian_id VARCHAR(6)  NOT NULL,
    verdict     VARCHAR(20) NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT fk_anomaly_feedback_incident FOREIGN KEY (incident_id) REFERENCES anomaly_incident (id) ON DELETE CASCADE,
    CONSTRAINT fk_anomaly_feedback_guardian FOREIGN KEY (guardian_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT uq_anomaly_feedback          UNIQUE (incident_id, guardian_id),
    CONSTRAINT chk_anomaly_feedback_verdict CHECK (verdict IN ('REAL', 'FALSE_ALARM'))
);

-- 상태 재계산은 상황 단위로 응답 전체를 읽는다(UNIQUE가 incident_id 선행이라 이 조회는 그 인덱스로 커버된다).
