-- 이상감지 판정 미응답 재촉 (2026-09-01)
--
-- 왜 필요한가: 판정(anomaly_incident.review_status)은 관리자 운영 자료라 응답률이 곧 자료의 질이다.
-- 그러나 답할 때까지 계속 쏘면 보호자가 앱 알림을 통째로 꺼버리고, 그 순간 그 집의 SOS·화재 알림까지
-- 함께 죽는다(복약 미복용 요약에서 이미 내린 판단). 그래서 강제가 아니라 절제된 재촉으로 간다.
--
-- 하이브리드: 상황이 닫힌 뒤 1시간 경과 + 여전히 PENDING이면 건별 1회 → 그 뒤로는 하루 1회 요약.
-- 축이 다르므로 테이블을 나눈다(복약의 medication_reminder_log ↔ medication_missed_alert_log와 같은 구조).

-- =============================================
-- 1. anomaly_review_reminder_log (건별 1차)
-- =============================================
-- 발송 "전"에 이 행을 먼저 커밋하고 보낸다(선점 후 발송). 순서를 뒤집으면 발송 직후 앱이 죽었을 때
-- 다음 주기에 또 보낸다 - 스케줄러가 5분마다 도므로 마감(3일) 내내 같은 재촉이 반복된다.
--
-- 상황당 보호자당 정확히 1건이라 attempt 컬럼을 두지 않는다. 2차 이후는 요약이라 축이 다르고,
-- 값이 항상 1인 컬럼은 "여러 번 보낼 수 있다"는 잘못된 여지를 남긴다.
CREATE TABLE anomaly_review_reminder_log (
    id          BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    incident_id BIGINT      NOT NULL,
    guardian_id VARCHAR(6)  NOT NULL,
    sent_at     TIMESTAMPTZ NOT NULL,

    CONSTRAINT fk_anomaly_reminder_incident FOREIGN KEY (incident_id) REFERENCES anomaly_incident (id) ON DELETE CASCADE,
    CONSTRAINT fk_anomaly_reminder_guardian FOREIGN KEY (guardian_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT uq_anomaly_review_reminder   UNIQUE (incident_id, guardian_id)
);

-- "이 보호자가 아직 안 답한 상황 중 이미 재촉한 것"을 요약 단계에서 조회한다.
CREATE INDEX idx_anomaly_reminder_guardian ON anomaly_review_reminder_log (guardian_id, incident_id);

-- =============================================
-- 2. anomaly_review_summary_log (하루 1회 요약)
-- =============================================
-- 축은 (보호자, 날짜)다 - 요약은 "그 보호자가 하루 한 번" 받는다. 상황 단위로 쪼개 건별 발송으로
-- 바꾸지 말 것: 알림 피로로 보호자가 앱 알림을 통째로 끄면 SOS·이상감지 같은 필수 알림까지 죽는다.
CREATE TABLE anomaly_review_summary_log (
    id            BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guardian_id   VARCHAR(6)  NOT NULL,
    summary_date  DATE        NOT NULL,   -- KST 기준
    pending_count INT         NOT NULL,   -- 그때 미응답이던 상황 수
    sent_at       TIMESTAMPTZ NOT NULL,

    CONSTRAINT fk_anomaly_summary_guardian FOREIGN KEY (guardian_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT uq_anomaly_review_summary   UNIQUE (guardian_id, summary_date)
);

-- =============================================
-- 3. guardian_anomaly_setting (보호자별 재촉 수신 여부)
-- =============================================
-- 보호자가 "이 알림만" 끌 수 있어야 한다. 그러지 못하면 알림 피로로 앱 알림을 통째로 꺼버리고,
-- 그때 SOS·이상감지 같은 필수 알림까지 함께 죽는다(guardian_medication_setting과 같은 이유).
--
-- 행이 없으면 애플리케이션 기본값(ON)을 따른다 → 기존 사용자 백필 불필요.
-- 복약 설정과 테이블을 합치지 않는다 - 축(복약은 보호자×피보호자, 재촉은 보호자 단위)도 도메인도 다르다.
CREATE TABLE guardian_anomaly_setting (
    id                      BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guardian_id             VARCHAR(6)  NOT NULL,
    review_reminder_enabled BOOLEAN     NOT NULL,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT fk_guardian_anomaly_setting_guardian FOREIGN KEY (guardian_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT uq_guardian_anomaly_setting          UNIQUE (guardian_id)
);
