-- 이상감지 판정 다수결 전환 + 동수 재확인 안내 + 관리자 정정 폐지 (2026-09-21)
--
-- 바뀐 규칙: 판정은 응답한 보호자의 다수결이다. 2:1이면 다수 쪽으로 정해지고 동수(1:1, 2:2)만 CONFLICTED다.
-- 동수는 보호자들이 다시 응답해 합의하는 것으로만 풀린다 - 관리자 정정(PATCH .../review, V46)은 폐지했다.
--
-- 남겨 두는 것:
--   - anomaly_incident.resolved_by·resolved_at·review_note: 폐지 전 정정 기록. 엔티티 매핑만 해제했다.
--     DROP은 비가역이라 별도 후속으로 미룬다.
--   - admin_audit_log CHECK의 ANOMALY_REVIEW_RESOLVE: 폐지 전 감사 로그 행이 이 값을 담고 있어 CHECK에서
--     빼면 재정의가 실패한다. enum도 그대로 둔다(새로 기록되지 않을 뿐).

-- =============================================
-- 1. anomaly_review_conflict_log (동수 재확인 안내)
-- =============================================
-- 상황이 동수가 되면 응답한 보호자에게 "다른 보호자와 판정이 다릅니다" 안내를 보호자당 한 번 보낸다.
-- 동수↔다수를 번복으로 오가도 다시 보내지 않는다(UNIQUE) - 재촉 절제 원칙(V45)과 같은 판단이다.
--
-- 선점 후 발송: 스케줄러가 이 행을 먼저 커밋하고 보낸다(V45와 같은 이유).
-- sent=false 행은 "보내지 않고 처리 완료"다 - 방금 답해 동수를 만든 보호자는 응답 API가 이미
-- CONFLICTED를 돌려줬으므로 안내하지 않고, 응답 트랜잭션에서 이 행만 남겨 스케줄러가 건너뛰게 한다.
CREATE TABLE anomaly_review_conflict_log (
    id          BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    incident_id BIGINT      NOT NULL,
    guardian_id VARCHAR(6)  NOT NULL,
    sent        BOOLEAN     NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL,

    CONSTRAINT fk_anomaly_conflict_incident FOREIGN KEY (incident_id) REFERENCES anomaly_incident (id) ON DELETE CASCADE,
    CONSTRAINT fk_anomaly_conflict_guardian FOREIGN KEY (guardian_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT uq_anomaly_review_conflict   UNIQUE (incident_id, guardian_id)
);

-- =============================================
-- 2. 기존 판정 재계산 (⚠️ 비가역 - 이전 상태값은 남지 않는다)
-- =============================================
-- 관리자가 정정한 건도 포함해 보호자 응답만으로 다시 정한다. 보호자 응답 원본은 그대로라 언제든 다시 셀 수 있다.
UPDATE anomaly_incident i
SET review_status = CASE
        WHEN f.real_count > f.false_count THEN 'REAL'
        WHEN f.real_count < f.false_count THEN 'FALSE_ALARM'
        ELSE 'CONFLICTED'
    END
FROM (
    SELECT incident_id,
           COUNT(*) FILTER (WHERE verdict = 'REAL')        AS real_count,
           COUNT(*) FILTER (WHERE verdict = 'FALSE_ALARM') AS false_count
    FROM anomaly_incident_feedback
    GROUP BY incident_id
) f
WHERE i.id = f.incident_id;

-- 응답이 한 건도 없는데 PENDING이 아닌 건은 관리자가 정정만 한 경우다 - 보호자 응답 기준으로 되돌린다.
UPDATE anomaly_incident i
SET review_status = 'PENDING'
WHERE i.review_status <> 'PENDING'
  AND NOT EXISTS (SELECT 1 FROM anomaly_incident_feedback f WHERE f.incident_id = i.id);

-- 기존 동수 건에는 안내를 보내지 않는다 - 규칙이 바뀐 시점의 과거 건까지 한꺼번에 푸시하면
-- 배포 직후 오래된 상황으로 알림이 몰린다. 이미 응답한 보호자 전원을 "처리 완료"로 기록해 둔다.
INSERT INTO anomaly_review_conflict_log (incident_id, guardian_id, sent, created_at)
SELECT f.incident_id, f.guardian_id, FALSE, now()
FROM anomaly_incident_feedback f
JOIN anomaly_incident i ON i.id = f.incident_id
WHERE i.review_status = 'CONFLICTED';
