-- 관리자 알림 이력 (2026-09-22)
--
-- 왜 필요한가: 알림이 실제로 전달됐는지, 실패했다면 왜인지를 관리자가 볼 곳이 없었다. 발송 결과는
-- 서버 stdout 로그에만 남아 조회할 수 없고, 기존 *_reminder_log는 중복 발송을 막으려고 "보내기 전에"
-- 적는 선점 기록이라 결과가 없다.
--
-- 한 행 = 알림 1건 × 수신자 1명. NotificationDispatcher가 발송을 마친 뒤 한 곳에서만 쓴다.
-- WebSocket 실시간 이벤트와 인증번호 문자는 디스패처를 거치지 않아 여기 남지 않는다.
-- 이 테이블 이전의 발송은 소급되지 않는다.

CREATE TABLE notification_log (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      TIMESTAMPTZ  NOT NULL,
    -- NotificationType 이름. 종류는 계속 늘어나므로 CHECK를 걸지 않는다(값 추가마다 재정의가 필요해진다).
    type            VARCHAR(40)  NOT NULL,
    recipient_id    VARCHAR(6)   NOT NULL,
    -- 이 알림이 어느 피보호자에 관한 것인가. 연결 수락·거절·해제, 문의 답변, 판정 요약은 특정할 수 없어 NULL.
    ward_id         VARCHAR(6),
    title           VARCHAR(200),
    body            TEXT,
    result          VARCHAR(20)  NOT NULL,
    not_sent_reason VARCHAR(30),
    -- 시도한 채널별 결과: [{"channel":"FCM","status":"FAILED","reason":"NO_DEVICE"}, ...]
    -- 사유는 고정 코드만 담는다 - 예외 원문(토큰·전화번호가 섞일 수 있음)은 저장하지 않는다.
    channel_results JSONB        NOT NULL DEFAULT '[]'::jsonb,

    -- 탈퇴자 데이터를 붙들지 않는다(이상감지 이력과 같은 판단). 수신자든 피보호자든 탈퇴하면 함께 지운다.
    CONSTRAINT fk_notification_log_recipient FOREIGN KEY (recipient_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_notification_log_ward      FOREIGN KEY (ward_id)      REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT chk_notification_log_result
        CHECK (result IN ('DELIVERED', 'SMS_FALLBACK', 'FAILED', 'NOT_SENT')),
    CONSTRAINT chk_notification_log_not_sent_reason
        CHECK (not_sent_reason IN ('RESTRICTED_ACCOUNT', 'WITHDRAWING_ACCOUNT', 'NO_ENABLED_CHANNEL')),
    -- 보내지 않았을 때만 사유가 있다.
    CONSTRAINT chk_notification_log_not_sent_pair
        CHECK ((result = 'NOT_SENT') = (not_sent_reason IS NOT NULL))
);

-- 관리자 목록은 기간 + 최신순이 기본이고, "전송 실패" 탭은 결과로 좁힌다.
CREATE INDEX idx_notification_log_created_at ON notification_log (created_at DESC);
CREATE INDEX idx_notification_log_result     ON notification_log (result, created_at DESC);
-- 탈퇴 시 CASCADE 삭제와 피보호자·수신자 검색을 위해.
CREATE INDEX idx_notification_log_recipient  ON notification_log (recipient_id);
CREATE INDEX idx_notification_log_ward       ON notification_log (ward_id);
