-- 이상감지 5초 영상 클립 (2026-10-04)
--
-- 위험(danger=true)으로 이력이 적재된 감지 중 클립 쿨다운(기본 5분)을 통과한 건마다 AI 서버에서 감지 앞 3초 + 뒤 2초
-- WebM을 받아 백엔드 디스크에 저장한다. 이 테이블은 그 파일의 메타만 담는다 - 영상 바이트는 DB에 넣지 않는다.
--
-- 파일 위치: 저장 루트(anomaly.clip.storage-dir) + file_name. 경로 전체가 아니라 서버가 만든 UUID 파일 이름만 저장한다 -
-- 저장 루트를 옮겨도 행을 고칠 필요가 없고, 사용자 입력이 경로에 섞일 여지가 없다.
--
-- 열람: 보호자 = 요청 시점 ACTIVE 연결 피보호자의 클립만 / 피보호자 본인 = ACTIVE 연결이 1건 이상일 때만.
-- 관리자는 열람하지 않는다(관리자 API·DTO에 클립 정보를 싣지 않는다).

CREATE TABLE anomaly_clip (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 판정 단위인 상황. 상황이 지워지면(피보호자 탈퇴 CASCADE) 클립 행도 함께 지워진다 - 파일은 탈퇴 리스너가 먼저
    -- 지우고, 리스너를 거치지 않는 스윕 purge 경로에서 남은 파일은 고아 청소가 회수한다.
    incident_id     BIGINT       NOT NULL,
    ward_id         VARCHAR(6)   NOT NULL,
    -- 카메라 삭제 시 그 카메라의 클립을 지우기 위한 키(감지 시점의 camera.session_id).
    session_id      VARCHAR(64)  NOT NULL,
    file_name       VARCHAR(64)  NOT NULL,
    size_bytes      BIGINT       NOT NULL,
    -- 아래 넷은 AI 응답 헤더 값이다. 헤더가 빠지거나 형식이 틀리면 NULL(모르는 값을 0으로 채우지 않는다).
    duration_ms     INTEGER,
    frame_count     INTEGER,
    width           INTEGER,
    height          INTEGER,
    -- 클립 첫 프레임 시각(AI X-Clip-Started-At). 없으면 NULL.
    clip_started_at TIMESTAMPTZ,
    -- AI에 요청한 감지 시각(AI analyzedAt, 없으면 요청 시각).
    detected_at     TIMESTAMPTZ  NOT NULL,
    -- VISIBLE = 열람 가능 / HIDDEN = 오탐 확정으로 비공개(24시간 뒤 청소가 물리 삭제, 그 안에 번복되면 VISIBLE로 복구).
    status          VARCHAR(20)  NOT NULL,
    hidden_at       TIMESTAMPTZ,
    created_at      TIMESTAMPTZ  NOT NULL,
    updated_at      TIMESTAMPTZ  NOT NULL,

    CONSTRAINT fk_anomaly_clip_incident FOREIGN KEY (incident_id) REFERENCES anomaly_incident (id) ON DELETE CASCADE,
    CONSTRAINT fk_anomaly_clip_ward     FOREIGN KEY (ward_id)     REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT uq_anomaly_clip_file     UNIQUE (file_name),
    CONSTRAINT chk_anomaly_clip_status  CHECK (status IN ('VISIBLE', 'HIDDEN')),
    -- 비공개일 때만 비공개 시각이 있다(24시간 유예의 기준점).
    CONSTRAINT chk_anomaly_clip_hidden_pair CHECK ((status = 'HIDDEN') = (hidden_at IS NOT NULL))
);

-- 상황별 클립 목록·대표 클립(최신)·상황당 상한 계산.
CREATE INDEX idx_anomaly_clip_incident   ON anomaly_clip (incident_id, created_at DESC);
-- 카메라 삭제·탈퇴 정리.
CREATE INDEX idx_anomaly_clip_ward       ON anomaly_clip (ward_id, session_id);
-- 오탐 비공개 24시간 경과 청소.
CREATE INDEX idx_anomaly_clip_hidden     ON anomaly_clip (status, hidden_at);
-- 보관 기간 만료 청소.
CREATE INDEX idx_anomaly_clip_created_at ON anomaly_clip (created_at);
