-- =============================================
-- V8: 보호자-피보호자 기능 추가
-- 1. connections.priority 컬럼 추가 (긴급통화 우선순위)
-- 2. fcm_tokens 테이블 생성 (FCM 푸시 토큰 관리)
-- =============================================

-- 1. connections 테이블에 priority 컬럼 추가
--    피보호자 기준 보호자 통화 우선순위 (1=1순위, 2=2순위, ...)
ALTER TABLE connections
    ADD COLUMN priority INT NOT NULL DEFAULT 1;

ALTER TABLE connections
    ADD CONSTRAINT chk_connections_priority CHECK (priority >= 1);

-- =============================================
-- 2. fcm_tokens (FCM 푸시 알림 토큰)
-- =============================================
CREATE TABLE fcm_tokens (
    id         BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id    VARCHAR(6)   NOT NULL,
    token      VARCHAR(500) NOT NULL,
    platform   VARCHAR(10)  NOT NULL DEFAULT 'ANDROID', -- ANDROID, IOS, WEB
    created_at TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    CONSTRAINT pk_fcm_tokens          PRIMARY KEY (id),
    CONSTRAINT uq_fcm_tokens_token    UNIQUE (token),
    CONSTRAINT fk_fcm_tokens_user     FOREIGN KEY (user_id)
        REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT chk_fcm_tokens_platform CHECK (platform IN ('ANDROID', 'IOS', 'WEB'))
);

CREATE TRIGGER trg_fcm_tokens_updated_at
    BEFORE UPDATE ON fcm_tokens
    FOR EACH ROW EXECUTE FUNCTION update_updated_at();

CREATE INDEX idx_fcm_tokens_user_id ON fcm_tokens(user_id);