name: CD

on:
  push:
    branches: [ dev ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: 배포
        run: |
          cd ~/SilverBridgeBe
          git pull origin dev
          docker compose -f docker-compose.dev.yml up -d --build api
