name: CI

on:
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v4

      - name: Gradle 빌드 검증
        run: ./gradlew build -x test --no-daemon
